# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
google-tracking-id: "UA-58305221-2"
title: Miguel Asencio
email: maasencioh@gmail.com
description: >
  This is my geek corner, a space to show my skills, interest and opinions.
  I hope you enjoy it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maasencioh.github.io" # the base hostname & protocol for your site
twitter_username:   maasencioh
github_username:    maasencioh
facebook_username:  miguel.bratsche
google_username:    +MiguelAsencio

# Page generation
subtitle: >
  This is my geek corner, a space to show my skills, <br>
  interest and opinions. I hope you enjoy it!

abilities:
  - icon: "code"
    title: "Javascript developer"
    content: "Develop 16 NPM packages with <a href='http://npm-stat.com/charts.html?package=&author=maasencioh&from=&to='>more than 14000 downloads</a> as a result of my intern in the <a href='https://www.epfl.ch/index.en.html'>EPFL</a>, working in datascience applied to chemistry and <a href='https://github.com/mljs/ml'>machine learning javascript packages</a>. I'm also very familiar with several javascript's based enviroments, like Node.js, Express, Koa.js, Mongoose, Angular.js, Ionic, among others."
  - icon: "android"
    title: "Mobile developer"
    content: "Developer in Android, IOS 8, hybrid apps and web apps. Unfortunatelly no one of them have seen the light, but there will be some releases soon."
  - icon: "bullhorn"
    title: "Communities"
    content: "Founder of <a href='meetup.com/Beer-JS-Bogota/'>Bogota BeerJS</a> community, reaching more than 100 members in one month, and co-funder of <a href='meetup.com/Big-Data-Science-Bogota'>Big Data and Data Science Bogota</a> meetup, reaching almost 1000 members. I'm also an active contributor of some free software projects, like the <a href='https://github.com/npellet/visualizer'>visualizer</a>."
  - icon: "industry"
    title: "Entepreneur"
    content: "Found my own software startup, developing 3 projects in the first year, applying the knowledge adquired in computer science's bachelor, the free software for entepreneur's diploma and several MOOCs of this toppics."

# atom feed
name: Miguel Asencio
author:
  name: Miguel Angel Asencio Hurtado
  email: maasencioh@gmail.com

# Build settings
markdown: kramdown

# gems
gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
